version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=shopwb
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../../backend-bwshop
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 8888:8888

# docker compose -p shopwb-nodejs-mysql up -d